
kind: Pod
apiVersion: v1
metadata:  
  name: test-pod
spec:  
  containers:  
  - name: test-pod    
    image: django-upload:1.0
    # 本地拉取镜像
    imagePullPolicy: Never  
    volumeMounts:      
      - name: pvc        
      # /upload存放上传资源的文件夹
        mountPath: "/var/www/upload/django/upload"  
    restartPolicy: "Never"  
    volumes:    
      - name: pvc      
        persistentVolumeClaim:        
          claimName: claim-local1
